ethertoff/urls.py
from django.urls import path, re_path
from . import views

## FIXME: if uncommenting url namespacing will be needed
# app_name = "ethertoff"

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.all, name='all'),
    path('manage/', views.manage, name='manage'),
    path('manage/<path:path>/', views.manage, name='manage'),
    path('publish/', views.publish, name='publish'),
    path('generate/', views.generate, name='generate'),
    path('index-labels/', views.index_labels, name='index-labels'),
    path('css-screen/', views.css, name='css-screen'),
    path('css-print/', views.cssprint, name='css-print'),
    path('css-offset/', views.offsetprint, name='css-offset'),
    path('css-slide/', views.css_slide, name='css-slide'),
    path('css-generator-screen/<path:folder>', views.css_generator_screen, name='css-generator-screen'),
    path('css-generator-print/<path:folder>', views.css_generator_print, name='css-generator-print'),
    path('javascript-generator/<path:folder>', views.javascript_generator, name='javascript-generator'),
    path('create/', views.padCreate, name='pad-create'),
    path('create/<path:prefix>/', views.padCreate, name='pad-create'),
    path('rename-folder/', views.RenameFolderView.as_view(), name='folder-rename'),
    path('rename-folder/<path:prefix>/', views.RenameFolderView.as_view(), name='folder-rename'),
    path('rename/<int:pk>/', views.padRename, name='pad-rename'),
    path('delete/<int:pk>/', views.padDelete, name='pad-delete'),
    path('public/<int:pk>/', views.padPublic, name='pad-public'),
    path('private/<int:pk>/', views.padPrivate, name='pad-private'),
    path('api/file/canonical-url/<int:pk>/', views.get_canoninical, name='get-canonical'),
    path('api/file/mime/<int:pk>/', views.get_mimetype, name='get-mime'),
    re_path('api/labels(/(?P<slug>[^/]+)?)$', views.labels, name='api-labels'),
    re_path(r'(?P<mode>[r|s|p])/(?P<slug>[^/]+)$', views.pad_read, name='pad-read'),
    re_path(r'(?P<mode>[r|s|p])/(?P<slug>[^/]+)$', views.pad_read, name='pad'),
    re_path(r'(?P<mode>[w])/(?P<slug>[^/]+)$', views.pad, name='pad'),
    re_path(r'w/(?P<slug>[^/]+)$', views.pad, name='pad-write'),
    re_path(r'^(?P<slug>[^/]+)\.xhtml$', views.xhtml, name='xhtml'),
]

my_project/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# This is to allow the website to work under a subfolder
# i.e. http://ethertoff.be/2015/
# Define SUBFOLDER in your local_settings.py
BASE_URL = '^'
try:
    BASE_URL = r'^' + settings.SUBFOLDER
    if BASE_URL and not BASE_URL.endswith(r'/'):
        BASE_URL += r'/'
except AttributeError:
    pass

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^filer/', include('filer.urls')),
    path('', include("ethertoff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns = [
    #path(BASE_URL , include(base_urlpatterns)),
#]

ethertoff/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    name         = forms.CharField(max_length=50, label=_("First Name"))
    email        = forms.EmailField(label=_("E-Mail"))
    subject      = forms.CharField(max_length=100, label=_("Subject"))
    message      = forms.CharField(widget=forms.Textarea(), label=_("Message"))

class RenameFolderForm(forms.Form):
    old_name = forms.CharField(label=_("Old name"), required=False)
    new_name = forms.CharField(label=_("New name"), required=False)

class RenamePadForm(forms.Form):
    pk = forms.HiddenInput()
    old_name = forms.CharField(label=_("Old name"), required=False)
    new_name = forms.CharField(label=_("New name"))

ethertoff/views.py
# -*- coding: utf-8 -*-

# Python imports
import datetime
import time
import urllib
from urllib.parse import urlparse
from html.parser import HTMLParser
import json
import re
import os

# PyPi imports

import markdown
# from mdx_semanticdata import SemanticDataExtension
from py_etherpad import EtherpadLiteClient
import dateutil.parser
import pytz

# Framework imports
from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError
from django.conf import settings
from django.contrib.staticfiles import finders

# Django Apps import

from etherpadlite.models import Pad, PadAuthor
from etherpadlite import config

from ethertoff.management.commands.index import snif
from ethertoff.templatetags.wikify import wikifyPath, ensureTrailingSlash

# Generator commands
from generator.management.commands.generate import generate as generateStatic
from generator.utils import discoverPublicationFolders
from generator.forms import makeGenerationForm
from labels.utils import index_labels as indexLabels, load_labels

from . import forms as ethertoffForms

from ethertoff.forms import RenameFolderForm, RenamePadForm
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from django.views.decorators.clickjacking import xframe_options_exempt

from ethertoff.utils import getPadMarkdown, getPadHtml, pathToSlug, discoverPad, stripLeadingAsterisks

from my_project.forms import PadCreateWithTemplate

from filer.models import File

# By default, the homepage is the pad called ‘start’ (props to DokuWiki!)
try:
    HOME_PAD = settings.HOME_PAD
except ImportError:
    HOME_PAD = 'About.md'
try:
    BACKUP_DIR = settings.BACKUP_DIR
except ImportError:
    BACKUP_DIR = None

"""
Set up an HTMLParser for the sole purpose of unescaping
Etherpad’s HTML entities.
cf http://fredericiana.com/2010/10/08/decoding-html-entities-to-text-in-python/
"""

try:
    h = HTMLParser()
    unescape = h.unescape
except AttributeError:
    import html
    unescape = html.unescape

"""
Create a regex for our include template tag
"""
include_regex = re.compile("{%\s?include\s?\"([\w._-]+)\"\s?%}")




# Perhaps move to the model?
def makePadPublic (pad, n=0):
    if not pad.is_public:
        epclient = EtherpadLiteClient(pad.server.apikey, settings.API_LOCAL_URL if settings.API_LOCAL_URL else pad.server.apiurl)
        tail = '' if n == 0 else '-{}'.format(n)
        publicid = pad.name+tail

        try:
            res = epclient.sendClientsMessage(pad.padid, "Please continue editing in the public version of this pad")
            print(res)
            res = epclient.copyPad(pad.padid, publicid)
            pad.is_public = True
            pad.publicpadid = publicid
            pad.save()

            return pad
        
        except ValueError:
            return makePadPublic(pad, n+1)

def makePadPrivate(pad):
    if pad.is_public:
        epclient = EtherpadLiteClient(pad.server.apikey, settings.API_LOCAL_URL if settings.API_LOCAL_URL else pad.server.apiurl)
        res = epclient.movePad(pad.publicpadid, pad.padid, force=True)

        pad.is_public = False
        pad.publicpadid = ''
        pad.save()
        return pad

# Filter out forbidden
def filterPadSlug(slug):
    # Replace spaces by '_'
    slug = re.sub(r'\s', '_', slug)
    # Replace forbidden characters
    slug = re.sub(r'[/]', '', slug)

    return slug 

def ensureExtension(slug):
    name, ext = os.path.splitext(slug)

    if settings.PAD_FORCE_EXTENSION:
        if ext.lower() not in settings.PAD_ALLOWED_EXTENSIONS:
            ext = settings.PAD_DEFAULT_EXTENSION

        return '{}{}'.format(name, ext.lower())

    return '{}{}'.format(name, ext.lower()) 

def insertNumberBeforeExtension (name, n=0):
    if n > 0:
        name, ext = os.path.splitext(name)
        name = '{}-{}'.format(name, n)

        return '{}{}'.format(name, ext)
    else:
        return name

def treatPadName(slug, n):
    return insertNumberBeforeExtension(
        ensureExtension(
            filterPadSlug(slug)), n)

def createPad (slug, server, group, n=0):
    if n < 25:
        try:
            safe_slug = treatPadName(slug, n)
            pad = Pad(
                name=slugify(safe_slug)[:42], # This is the slug internally used by etherpad
                display_slug=safe_slug, # This is the slug we get to change afterwards
                server=group.server,
                group=group
            )

            pad.save()
            return pad
        except ValueError:
            # Pad already exists on the server
            return createPad(slug=slug, server=server, group=group, n=n+1)
        except IntegrityError:
            # Pad existed in the database, but not on the server
            # delete the created pad
            pad.Destroy()
            return createPad(slug=slug, server=server, group=group, n=n+1)

    return False

# Move as a property to the model ?
def getFolderName (slug):
    if settings.PAD_NAMESPACE_SEPARATOR in slug:
        return slug.rsplit(settings.PAD_NAMESPACE_SEPARATOR, 1)[0]
    else:
        return None

@login_required(login_url='/accounts/login')
def padCreate(request, prefix=''):
    """
    Create a pad
    """    
    
    # normally the ‘pads’ context processor should have made sure that these objects exist:
    author = PadAuthor.objects.get(user=request.user)
    group = author.group.all()[0]
    
    if request.method == 'POST':  # Process the form
        form = PadCreateWithTemplate(request.POST)
        if form.is_valid():
            slug = re.sub(r'\s+', '_', form.cleaned_data['name'])
            slug = slug.strip(":")  # avoids leading and trailing "::"
            pad = createPad(slug=slug, server=group.server, group=group)

            if pad:
                if form.cleaned_data['template'] != 'none':
                    try:
                        templatePad = Pad.objects.get(name=form.cleaned_data['template'])                    
                        template = getPadHtml(templatePad)
                        epclient = EtherpadLiteClient(pad.server.apikey, settings.API_LOCAL_URL if settings.API_LOCAL_URL else pad.server.apiurl)
                        epclient.setHtml(pad.padid, template)
                    except Pad.DoesNotExist:
                        pass
                    
                return HttpResponseRedirect(reverse('pad-write', args=(pad.display_slug,) ))
    else: 
        # No form to process so create a fresh one
        # prefix should contain the name of the folder
        form = PadCreateWithTemplate({'group': group.groupID, 'name': wikifyPath(ensureTrailingSlash(prefix) if prefix else '')})

    con = {
        'form': form,
        'pk': group.pk,
        'title': _('Create pad in %(grp)s') % {'grp': group}
    }
    con.update(csrf(request))
    return render(
        request,
        'pad-create.html',
        con,
    )


@login_required(login_url='/etherpad')
def padDelete(request, pk):
    """Delete a given pad
    """
    pad = get_object_or_404(Pad, pk=pk)

    # Any form submissions will send us back to the profile
    if request.method == 'POST':
        if 'confirm' in request.POST:
            pad.delete()
        return HttpResponseRedirect('/manage/')

    con = {
        'action': reverse('pad-delete', kwargs={'pk': pk}),
        'question': _('Really delete the pad {}?'.format(str(pad))),
        'title': _('Deleting {}'.format(str(pad))),
        'label': _('Delete')
    }
    con.update(csrf(request))
    return render(
        request,
        'pads/confirm.html',
        con
    )


"""
    Renames a pad to the given slug.
    If the desired name already exists a number is added before the extension.
    name.md → name-1.md
"""
def renamePad(pad, slug, n=0):
    pad.display_slug = treatPadName(slug, n)
    
    while n < settings.MAX_PAD_SAVE_TRIES:
        try:
            return pad.save()
        except IntegrityError:
            return renamePad(pad, slug, n+1)

    raise IntegrityError

@login_required(login_url='/etherpad')
def padRename(request, pk):
    pad = get_object_or_404(Pad, pk=pk)

    if request.method == 'POST':
        form = ethertoffForms.RenamePadForm(request.POST)
        if form.is_valid():
            slug = re.sub(r'\s+', '_', form.cleaned_data['new_name'])
            slug = slug.strip(":")  # avoids leading and trailing "::"
            renamePad(pad, slug)

            path = getFolderName(pad.display_slug)

            if path:
                path = path.replace(settings.PAD_NAMESPACE_SEPARATOR, '/')
                return redirect('manage', path=path)
            else:
                return redirect('manage')

    else:
        print(pad.pk)
        form = ethertoffForms.RenamePadForm({
            'pk': pad.pk,
            'old_name': pad.display_slug,
            'new_name': pad.display_slug,
        })

    context = {
        'form': form,
        'pk': pad.pk,
        'title': _('Rename pad {}').format(str(pad))
    }

    context.update(csrf(request))

    return render(
        request,
        'pad-rename.html',
        context
    )

class RenamePadView(FormView):
    template_name = 'pad-rename.html'
    form_class = RenamePadForm

class RenameFolderView(FormView):
    template_name = 'folder-rename.html'
    form_class = RenameFolderForm
    success_url = reverse_lazy('manage')

    def get_initial(self):
        """Return the initial data to use for forms on this view."""
        old_name = self.kwargs.get("prefix", "") 
        old_name = old_name.replace('/', settings.PAD_NAMESPACE_SEPARATOR)

ethertoff/templates/all.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <ul id="pads_list">
        {% for pad in pads %}
            <li><a data-uid="{{ pad.display_slug }}" href="{% if mode == 'write' %}{% url 'pad-write' slug=pad.display_slug %}{% else %}{% url 'pad-read' 'r' pad.display_slug %}{% endif %}" class="pad-link">{{ pad.display_slug|dewikify }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

ethertoff/templates/base.html
{% load wikify ethertoff_tags static generator_utils %}<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" {% if meta.language %} lang="{{ meta.language.0 }}" {% endif %} moznomarginboxes mozdisallowselectionprint>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}" type="text/css" media="all">
    
    {% block extra_styles %}
        <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
        <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
    {% endblock %}

    <script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"> </script>
    <script src="{% static 'js/underscore.js' %}" type="text/javascript"> </script>

    {% block head_meta %}{% endblock %}

    <title>{{ site_name }}{% if pad %} → {{ pad.display_slug|dewikify }}{% endif %}</title>
    
</head>
<body class="pad-{{ pad.display_name|slugify }} {{ mode }}-mode {% if user.is_authenticated and author %}logged-in{% else %}logged-out{% endif %} {% block bodyclasses %}{% endblock %}">
    <nav id="nav-left">
        <h1><a id="logo" data-article="{% block data_article %}{% endblock%}" href="/">{{ site_name }}</a></h1>
        <!-- <a class="button--nav screen-only" href="/r/About.md">About</a> -->
        
        <!-- 
        <div id="sort-by">Sort by:
            <a class="{% if sort == 'date' %}active{% endif %} button screen-only" href="/?sort=date">Date</a>
            <a class="{% if sort == 'tags' %}active{% endif %} button screen-only" href="/?sort=tags">Tag</a>
            <a class="{% if sort == 'authors' %}active{% endif %} button screen-only" href="/?sort=authors">Author</a>
        </div>-->
        {% block extra_nav %}{% endblock %}
        
        <a class="button--nav screen-only" href="{% url 'all' %}">List</a>

        {% if user.is_authenticated and author %}
        <div id="staff-menu" class="private">
            <span class="screen-only">{{ author.full_name_with_prefix }}</span>
            <a class="button--nav screen-only" href="{% url 'logout' %}{% if pad %}?next={% url 'pad-read' 'r' pad.display_slug %}{% endif %}">Log out</a>
            <a class="button--nav screen" href="{% url 'password_change' %}">Change password</a>
            <a class="button--nav screen-only" href="{% url 'pad-create' %}">Create Pad</a>
            <a class="button--nav screen-only" href="{% url 'admin:filer-directory_listing-root' %}" target="_blank">File manager</a>
            <a class="button--nav screen-only" href="{% url 'index-labels' %}">Update labels</a>
            <a class="button--nav screen-only" href="{% url 'generate' %}">Generate publications</a>
            <!-- <a class="button--nav screen-only" href="{% generated_site_url %}">View static version</a> -->
            <!-- <a class="button--nav screen-only" href="{% generated_site_debug_url %}">View debug information</a> -->
            <!-- <a class="button--nav screen-only" href="/w/screen.css">screen.css</a> -->
            <!-- <a class="button--nav screen-only" href="/w/laser.css">laser.css</a> -->
            <!-- <a class="button--nav screen-only" href="/w/offset.css">offset.css</a> -->
            <!-- <a class="button--nav screen-only" href="/w/documentation.md">documentation</a> -->
            {% else %}
            <a class="button--nav" href="{% url 'login' %}">Log in</a>
            {% endif %}
            
        </div>
    </nav>
    <nav id="nav-right">
        {% if user.is_authenticated %}
        <details class="publications publication-list">
            <summary class="button--nav">Publications</summary>
            <div class="publication-list--content">
                {% for publication in publications %}
                    <a class="button--nav screen-only" href="{{ publication.url }}">{{ publication.title|striptags }}</a>
                {% endfor %}
            </div>
        </details>
        {% endif %}
    </nav>
    <!--
    <nav id="nav-right">
        {% if pad %}
            <a class="button--nav screen-only read-button" href="{% url 'pad-read' 'r' pad.display_slug %}">Read</a>
            <a class="button--nav screen-only slide-button" href="{% url 'pad-read' 's' pad.display_slug %}">Slide</a>
            <a class="button--nav screen-only" href="{% url 'pad-read' 'p' pad.display_slug %}">Print</a>
            {% if pad.is_public or user.is_authenticated %}
                <a class="button--nav screen-only write-button" href="{% url 'pad-write' pad.display_slug %}">Write</a>
            {% else %}
                <a class="button--nav screen-only write-button login-required" href="{% url 'login' %}">Write</a>
            {% endif %}
        {% endif %}
    </nav>
    -->

    <aside id="title-left" class="left-side screen-only">
        {% block title_left %}{% endblock %}
    </aside>

    <header id="title" class="middle">
        {% block title %}{% endblock %}
    </header>

    <aside id="title-right" class="right-side screen-only">
        {% block title_right %}{% endblock %}
    </aside>
    <aside id="content-left" class="left-side screen-only">
        {% block leftside %}{% endblock %}
    </aside>
    <main id="content" class="middle {% block contentclasses %}{% endblock %}">
        {% block content %}{% endblock %}
    </main>
    <aside id="content-right" class="right-side screen-only">
        {% block rightside %}{% endblock %}
    </aside>
    {% block extraui %}{% endblock %}

    <footer id="footer"></footer>

    <script src="{% static 'js/ethertoff.js' %}" type="text/javascript" charset="utf-8"> </script>
    <script src="{% static 'js/comments/comments.js' %}" type="text/javascript" charset="utf-8"> </script>

    {% if user.is_authenticated and author %}
        <script>
            $(function() {
                $("#content").revealComments();
            });
        </script>
    {% endif %}


    {% block scripts %}{% endblock %}
</body>
</html>

ethertoff/templates/folder-rename.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_styles %}
      <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
      <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}

{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
      <form action="{% url 'folder-rename' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                  {{ form.old_name.label_tag }}{{ form.old_name.value }}
            </div>
            <div class="form-row">
                  {{ form.new_name.label_tag }}{{ form.new_name }}
            </div>
            <div class="form-row--button">
                  {{ form.old_name.as_hidden }}
                  <input class="submit" type="submit" value="{% trans "Rename" %}" />
            </div>
      </form>
      <legend></legend>
{% endblock %}

ethertoff/templates/form.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>ethertoff</title>
    <link rel="stylesheet/less" href="{% static 'less/ethertoff.less' %}" type="text/css" media="screen" charset="utf-8">
    <script src="{% static 'js/less-1.4.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
<form id="email-form" action="{% url 'ethertoff-issue-send' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div>
        <input style="width: 45%; display: inline; margin-right: 10px;" id="id_name" maxlength="50" name="name" type="text" value="{{ user.get_full_name }}"/>
        <!--<input style="width: 45%; display: inline;" id="id_email" name="email" type="text" value="{{ user.email }}" />-->
    </div>
    <div style="margin-top: 3px;">
        <label style="width: 25%; display: inline;" for="id_subject">Subject</label> 
        <input style="width: 73%; display: inline;" id="id_subject" maxlength="100" name="subject" type="text" />
    </div>
    <div style="margin-top: 3px;">
        <textarea style="width: 96%; height: 6em;" id="id_message" name="message"></textarea>
    </div>
    <p><input type="submit" value="Send"></p>
</form>
</body>
</html>

ethertoff/templates/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<h1>{% trans "Logout" %}</h1>
{% endblock %}

{% block content %}
<h2>{% trans "You have been logged out." %} <a href="{% url 'login' %}">{% trans "Log back in." %}</a></h2>

{% endblock %}

ethertoff/templates/manage-tree.html
{% extends "base.html" %}
{% load wikify %}
{% block title %}
  <h2>Pads</h2>
{% endblock %}
{% block content %}
    <section class="pad-list--path">
        <a href="{% url 'manage' %}">root</a>
        {% for name, path in crumbs %}
            {% if path %}
              <span class="pad-list--path--separator"></span>
              <a href="{% url 'manage' path|pathString  %}">{{ name }}</a>
            {% endif %}
        {% endfor %}
        {% if currentPath %}
          <a href="{% url 'pad-create' currentPath|pathString %}" class="button push">+ create pad</a>
        {% else %}
          <a href="{% url 'pad-create' %}" class="button push">+ create pad</a>
        {% endif %}
    </section>
    <ul id="pads_list" class="manage_list">
        {% for key, type, object in dir_list %}
            {% if type == 'pad' %}
              <li class="pad"><a data-uid="{{ object.display_slug }}" href="{% url 'pad' mode=PAD_OPEN_MODE slug=object.display_slug %}" class="pad-link">{{ object.display_slug|stripPath:currentPath|dewikify }}{% if object.is_public %} (public){% endif %}</a>
                <section class="actions">
                  {% if object.is_public %}
                      <a href="{% url 'pad-private' object.pk %}" class="button button--private">make private</a>
                  {% else %}
                      <a href="{% url 'pad-public' object.pk %}" class="button button--public">make public</a>
                  {% endif %}
                  <a href="{% url 'pad-rename' object.pk %}" class="button button--rename">rename</a>
                  <a href="{% url 'pad-delete' object.pk %}" class="button button--delete">delete</a>
                </section>
              </li>
            {% else %}
              <li class="folder"><a href="{% url 'manage' key|addPath:currentPath %}">{{ key }}</a>
                <section class="actions">
                  <a href="{% url 'folder-rename' key|addPath:currentPath %}" class="button button--rename">rename</a>
                </section>
              </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

ethertoff/templates/manage.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <ul id="pads_list" class="manage_list">
        {% for pad in pads %}
            <li>
              <a data-uid="{{ pad.display_slug }}" href="{% if mode == 'write' %}{% url 'pad-write' slug=pad.display_slug %}{% else %}{% url 'pad-read' 'r' pad.display_slug %}{% endif %}" class="pad-link">{{ pad.display_slug|dewikify }}</a>
              <section class="actions">
                <a href="{% url 'pad-delete' pad.pk %}" class="button button--delete">delete</a>
              </section>
            </li>
        {% endfor %}
    </ul>

    <section class="pagination">
      <section class="step-links previous">
        {% if pads.has_previous %}
            <a href="{% url 'manage' 1 %}">&laquo; first</a>
            <a href="{% url 'manage' pads.previous_page_number %}">previous</a>
        {% endif %}
      </section>
    
      Page {{ pads.number }} of {{ pads.paginator.num_pages }}
    
      <section class="step-links next">
          {% if pads.has_next %}
              <a href="{% url 'manage' pads.next_page_number %}">next</a>
              <a href="{% url 'manage' pads.paginator.num_pages %}">last &raquo;</a>
          {% endif %}
      </section>
    </section>
{% endblock %}

ethertoff/templates/pad-public.html
{% extends "base.html" %}
{% load ethertoff_tags wikify generator_utils %}

{% block extra_styles %}
  <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
  <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}

{% block title %}
    <header>
    {% if meta.authors %}
        <p class="authors">{{ meta.authors|natural_join:'et' }}</p>
    {% endif %}
    <h1>
        {{ meta.title.0|default:pad.display_slug }}
    </h1>
    </header>
{% endblock %}

{% block content %}
  {% if error %}
  <div id="main">
    <div id="errors">
      <h2>Errors:</h2>
      <p>{{error}}</p>
    </div>
  </div>
  {% else %}
  <section class="pad-list--path">
    <a href="{% url 'manage' %}">root</a>
    {% for name, path in crumbs %}
        {% if not forloop.last %}
        > <a href="{% url 'manage' path|pathString  %}">{{ name }}</a>
        {% else %}
        > {{ name }}
        {% endif %}
    {% endfor %}
  </section>
  <iframe id="ether" src="{{link}}{% if uname %}?userName={{uname}}{% endif %}"> </iframe>
  {% endif %}

{% endblock %}


{% block rightside %}
  {% include "partials/markdown-guide.html" %}
{% endblock %}

ethertoff/templates/pad-rename.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_styles %}
      <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
      <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}

{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
      <form action="{% url 'pad-rename' pk=pk %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                  {{ form.old_name.label_tag }}{{ form.old_name.value }}
            </div>
            <div class="form-row">
                  {{ form.new_name.label_tag }}{{ form.new_name }}
            </div>
            <div class="form-row--button">
                  <input class="submit" type="submit" value="{% trans "Rename" %}" />
            </div>
      </form>
      <legend></legend>
{% endblock %}